# Generated by Django 2.2.2 on 2019-09-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20190924_1150'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blogposts',
        ),
    ]
