# Generated by Django 2.2.2 on 2019-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20190924_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('posts', models.ManyToManyField(to='qa.Post')),
            ],
        ),
    ]
